version: '3'
services:
  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - app-network

  server:
    build: ./
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    environment:
      NODE_ENV: production
    depends_on:
      - kafka
      - zookeeper
    command: npm start
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
